# Site settings
title: Marinucci Medical Centre | An Inner West General Practice
description: "An Inner West General Practice."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Marinucci Medical Centre
    hero_description: An Inner West General Practice

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: (02) 9798 4835
    fax: (02) 9798 0714
    emergency: Dial 000
    email: marinuccimedical@gmail.com
    address: 68 Ramsay Street, <br> Haberfield NSW 2045

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 09:00 – 15:00
sunday: Closed

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 15
    address: 68 Ramsay Street, Haberfield, NSW Australia
    address_details: svg/min/logo.svg

# Social settings
# facebook: http://facebook.com
# twitter: http://twitter.com
# instagram: http://instagram.com
# youtube: http://youtube.com
# skype: skype:obaez_design?userinfo
# feed: yes

# Footer
copyright: © 2017 Marinucci Medical Centre - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
